version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://afk_admin:secretpassword@db:5432/afk_database?schema=public
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15-alpine
    container_name: afk_helper_db
    restart: always
    environment:
      - POSTGRES_USER=afk_admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=afk_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: