version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: arizona_backend
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://afk_admin:${DB_PASSWORD}@db:5432/afk_database?schema=public
    depends_on:
      - db

  caddy:
    image: caddy:2-alpine
    container_name: caddy_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: arizona-afk_helper_db
    restart: always
    environment:
      - POSTGRES_USER=afk_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=afk_database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  caddy_data:
  caddy_config: