export const iconMap = {
  ':envelope:': '/icons/envelope.png',
  ':pushpin:': '/icons/pushpin.png',

  ':buy:': '/icons/buy.png',
  ':trade:': '/icons/trade.png',
  ':sell:': '/icons/sell.png',
  ':rent:': '/icons/rent.png',

  ':la:': '/icons/la.png',
  ':lb:': '/icons/lb.png',
  ':lc:': '/icons/lc.png',
  ':ld:': '/icons/ld.png',
  ':le:': '/icons/le.png',
  ':lf:': '/icons/lf.png',
  ':lg:': '/icons/lg.png',
  ':lh:': '/icons/lh.png',
  ':li:': '/icons/li.png',
  ':lj:': '/icons/lj.png',
  ':lk:': '/icons/lk.png',
  ':ll:': '/icons/ll.png',
  ':lm:': '/icons/lm.png',
  ':ln:': '/icons/ln.png',
  ':lo:': '/icons/lo.png',
  ':lp:': '/icons/lp.png',
  ':lq:': '/icons/lq.png',
  ':lr:': '/icons/lr.png',
  ':ls:': '/icons/ls.png',
  ':lt:': '/icons/lt.png',
  ':lu:': '/icons/lu.png',
  ':lv:': '/icons/lv.png',
  ':lw:': '/icons/lw.png',
  ':lx:': '/icons/lx.png',
  ':ly:': '/icons/ly.png',
  ':lz:': '/icons/lz.png',

  ':K:': '/icons/K.png',
  ':KK:': '/icons/KK.png',
  ':M:': '/icons/M.png',

  ':k:': '/icons/K.png',
  ':kk:': '/icons/KK.png',
  ':m:': '/icons/M.png',
};
