export const chatLog = [
  {
    id: 1,
    time: '08:54:59',
    tag: null,
    tagColor: null,
    author: 'Dantes_Winchester',
    playerId: '373',
    nickNameColor: '#FFFFFF',
    text: 'не шарю в ценах',
    textColor: '#B7AFAF',
  },
  {
    id: 2,
    time: '08:55:04',
    tag: '[VIP ADV]',
    tagColor: '#FFFFFF',
    author: 'Vizard_Shakur',
    playerId: '353',
    nickNameColor: '#FFFFFF',
    text: ':lavka22: продаются акссесуары Фрирен по выгодным ценам',
    textColor: '#FFFFFF',
  },
  {
    id: 3,
    time: '08:55:04',
    tag: '[VIP] Объявление:',
    tagColor: '#FCAA4D',
    author: null,
    playerId: null,
    nickNameColor: null,
    text: 'Проходит собеседование в СМИ г.Лас-Вентурас на 6 должность. Ждем вас!. Frank_Hudson[250] Тел. 7677031',
    textColor: '#FCAA4D',
  },
  {
    id: 4,
    time: '08:58:41',
    tag: '[Семья]',
    tagColor: '#1DBAF2',
    author: '[8] Mad Dog Dexter_Morgon',
    playerId: '168',
    nickNameColor: '#1DBAF2',
    text: 'Точилки,Скины,Легендарный Аксы,и т.д по приятным ценам в :lavka2:',
    textColor: '#B9C1B8',
  },
  {
    id: 5,
    time: '09:00:00',
    tag: '[Аэропорт Лос Сантос]',
    tagColor: '#FFFFFF',
    author: null,
    playerId: null,
    nickNameColor: null,
    text: 'Уважаемые жители, открыта продажа билетов на рейс: Лос Сантос — Вайс Сити.',
    textColor: '#FFFFFF',
  },
  {
    id: 6,
    time: '09:16:43',
    tag: 'A:',
    tagColor: '#FF6347',
    author: 'Dmitry_DiCaprio',
    playerId: '332',
    nickNameColor: '#FF6347',
    text: 'установил в оффлайне 120 минут деморгана игроку Dantes_Winchester. Причина: офф от рп // D.Camp',
    textColor: '#FF6347',
  },
];
